apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: template.html
  template:
    metadata:
      labels:
        app: template.html
    spec:
      containers:
      - name: my-app-container
        image: anjelgevorg7/my-project:latest
        ports:
        - containerPort: 80
