name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'template.html'
      - 'Dockerfile'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t anjelgevorg7/my-project:latest .
        docker push anjelgevorg7/my-project:latest
      env:
        DOCKER_BUILDKIT: 1
